# -*- coding: utf-8 -*-
"""Billionaires_analysis_eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-E4QbnMHF2aM3BV_-lZw1y_6SsYahiOp
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
up= files.upload()

df= pd.read_csv('Forbes Billionaire.csv', encoding= 'unicode_escape')
df.head()

df.describe()

df.info()

df.isna().sum()

#Histogram plot
plt.figure(figsize=(20,10))
sns.histplot(x='Networth', data= df, color='purple')
plt.show()

plt.figure(figsize=(20,10))

sns.histplot(x='Age',data=df, color='red')
plt.show()

a= df['Industry'].value_counts().head()
a

Index= a.index
Index

Values= a.values
Values

plt.figure(figsize=(6,6))
plt.pie(Values, labels= Index, colors=['pink', 'green', 'purple','yellow', 'red'])
plt.title('Top 5 Industries',fontsize=18)
plt.show()

b= df['Country'].value_counts().head()
b
Index1= b.index
Index1
Values1= b.values
Values1
plt.figure(figsize=(6,6))
plt.pie(Values1, labels= Index1, colors=['yellow', 'orange', 'green', 'blue', 'purple'])
plt.title('Top 5 Countries containing Billionaires', fontsize=18)
plt.show()

c= df['Source'].value_counts().head()
c
Index2= c.index
Index2
Values2= c.values
Values2
plt.figure(figsize=(10,5))
plt.bar(Index2, Values2, color='purple')
plt.title('Top Sources',fontsize=18)
plt.show()

d= df['Age'].value_counts().head()
d
Index3= d.index
Index3
Values3= d.values
Values3
plt.figure(figsize=(10,5))
plt.bar(Index3, Values3,color=['purple','red','orange','yellow','brown'])
plt.title('Age Category of Billionaires', fontsize= 22)
plt.show()

